server:
  port: 8082

spring:
  application:
    name: processor-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: processor
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # Batch / throughput tuning
      properties:
        max.poll.records: 1000
        fetch.min.bytes: 1048576
        fetch.max.wait.ms: 50
      auto-offset-reset: earliest

  datasource:
    url: jdbc:postgresql://localhost:55432/eventsdb?reWriteBatchedInserts=true
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

# S3 Configuration
s3:
  enabled: ${S3_ENABLED:false}
  bucket:
    name: ${S3_BUCKET_NAME:realtime-analytics-yongqi}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
